# <font color = "#6585e7"><b>Numpy A to Z</b></font>

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy, short for Numerical Python, is an essential library in the Python ecosystem for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy serves as the foundation for a variety of scientific computing libraries, such as SciPy (for scientific computing), Pandas (for data analysis), and Matplotlib (for data visualization).

### <b>Creating Array in Python</b>

In [1]:
import array

# syntax : 
# array.array(typecode, [Initializers]), typecodes = i, f, d, u, l, b, B, h, H for int, float, double, unicode, long, signed char, unsigned char, short, unsigned short respectively
arr = array.array('i', [1, 2, 3, 4, 5]) # this will create an array of integers
print("The new created array is : ", arr)

The new created array is :  array('i', [1, 2, 3, 4, 5])


In [2]:
arr_float = array.array('f', [1.1, 2.2, 3.3, 4.4, 5.5]) 
print("The new created array is : ", arr_float)

The new created array is :  array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432, 5.5])


In [3]:
a = array.array('i', [1, 2, 3, 4, 5])
b = array.array('i', [6, 7, 8, 9, 10])
c = a + b # concatenation of two arrays
c

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [4]:
# adding the elements of two arrays
d = array.array('i', [0, 0, 0, 0, 0])
for i in range(len(a)):
    d[i] = a[i] + b[i]
print("The new created array is : ", d)

The new created array is :  array('i', [7, 9, 11, 13, 15])


## <b>Creating Numpy array</b>

In [5]:
import numpy as np # np is a standard alias for numpy

### <b>Creating an numpy array using list, tuple, range, etc</b>

In [6]:
l = [1, 2, 3, 4, 5]
arr1 = np.array(l)

t = (1, 2, 3, 4, 5)
arr2 = np.array(t)

arr3 = np.array(range(1, 6))
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


### <b>Creating an numpy array using arange, linspace, etc</b>

In [7]:
arr = np.arange(1, 6) # this will create an array of 1 to 5 like range function
print(arr)

arr = np.linspace(1, 5, 5) # this will create an array of 1 to 5 with 5 equally spaced elements
print(arr)

arr = np.linspace(1, 5, 10) # this will create an array of 1 to 5 with 10 equally spaced elements, difference between two consecutive elements will be same
print(arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### <b>Creating other types of arrays</b>

In [8]:
# creating an array of constant values

arr = np.full(5, 10) # this will create an array of 5 elements with all elements as 10
print(arr)

[10 10 10 10 10]


In [9]:
arr = np.empty(5, dtype=int) # this will create an array of 5 elements with random values of integer type
print(arr)

[0 0 0 0 0]


### <b>Creating Multidimensional Arrays</b>

In [10]:
# Creaing 2d array
# with 2d list, tuple

l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(l)
print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Creaing 3d array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


---

### <b>Shape, Size, Dtype and Ndim</b>

In [12]:
# checking the shape of the array, shape method will return the shape of the array
print(f"Shape of the arr: {arr.shape}")

# checking the size of the array, size method will return the total number of elements in the array
print(f"Size of the arr: {arr.size}")

# checking the dimension of the array, ndim is used to check the dimension of the array
print(f"Dimension of arr: {arr.ndim}")

Shape of the arr: (2, 2, 3)
Size of the arr: 12
Dimension of arr: 3


In [13]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr1: {arr1.ndim}")
print(f"Dimension of arr2: {arr2.ndim}")
print(f"Dimension of arr3: {arr3.ndim}")

Dimension of arr1: 1
Dimension of arr2: 2
Dimension of arr3: 3


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=float)
print(arr)
print(f"Array shape: {arr.shape}")
print(f"Size of Array: {arr.size}")
print(f"Itemsize of the Array: {arr.itemsize}")
print(f"Datatype of the Array: {arr.dtype}")
print(f"Dimension of arr: {arr.ndim}")

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Array shape: (2, 5)
Size of Array: 10
Itemsize of the Array: 8
Datatype of the Array: float64
Dimension of arr: 2


In [15]:
arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]], dtype=float)
print(arr)
print(f"Array shape: {arr.shape}")
print(f"Size of Array: {arr.size}")
print(f"Itemsize of the Array: {arr.itemsize}")
print(f"Datatype of the Array: {arr.dtype}")
print(f"Dimension of arr: {arr.ndim}")

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20.]]]
Array shape: (2, 2, 5)
Size of Array: 20
Itemsize of the Array: 8
Datatype of the Array: float64
Dimension of arr: 3


### <b>Zeros and Ones Array</b>

In [16]:
# creating an array of ones, zeros and empty array

arr = np.ones(5) # this will create an array of 5 elements with all elements as 1
print(arr)

arr = np.zeros(5) # this will create an array of 5 elements with all elements as 0
print(arr)

arr = np.empty(5) # this will create an array of 5 elements with random values
print(arr)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [17]:
zeros = np.zeros((2, 3)) # 2D array of zeros
print("2D array of Zeros:")
print(zeros)

print()
zeros = np.zeros((2, 3, 4)) # 3D array of zeros
print("3D array of Zeros:")
print(zeros)

2D array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

3D array of Zeros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### <b>Linspace and Logspace</b>

In [26]:
# Linspace : this function is used to create an array of evenly spaced values over a specified range
# syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# start: the starting value of the sequence
# stop: the end value of the sequence
# num: the number of samples to generate, default is 50
# endpoint: if true, stop is the last sample, otherwise, it is not included
# retstep: if true, return (samples, step), where step is the spacing between samples
# dtype: the type of the output array
# axis: the axis in the result to store the samples

# creating an array of evenly spaced values

print("Creating array using Linspace:")
arr1 = np.linspace(1, 5, 5) # this will create an array of 1 to 5 with 5 equally spaced elements
print(arr1)

# Logspace: this function is used to create an array of evenly spaced values on a log scale
# syntax: np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# Base: the base of the log space, default is 10.0

print("Creating array using Logspace:")
arr2 = np.logspace(1, 5, 5) # this will create an array of 1 to 5 with 5 equally spaced elements
print(arr2)


Creating array using Linspace:
[1. 2. 3. 4. 5.]
Creating array using Logspace:
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


### <b>Arrays Indexing and Slicing</b>

In [19]:
# Indexing in 1D array
# indexing in 1D array is similar to the indexing in python list, index start with zeor

arr = np.arange(1, 10)
print(arr)
print(f'First element of the array: {arr[0]}')
print(f'Second element of the array: {arr[1]}')
print(f'Last element of the array: {arr[-1]}')

[1 2 3 4 5 6 7 8 9]
First element of the array: 1
Second element of the array: 2
Last element of the array: 9


In [20]:
# Slicing of array is also similar to python list
a = arr[2:6] # index start with 0
print(arr)
print(a)

[1 2 3 4 5 6 7 8 9]
[3 4 5 6]


In [21]:
# Indexing in 2D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print("Indexing in 2D array:")
print(f'Element at 0th row and 0th column: {arr[0, 0]}')
print(f'Element at 0th row and 1st column: {arr[0, 1]}')
print(f'Element at last row and last column: {arr[-1, -1]}', end="\n\n")

print("Slicing in 2D array:", end="\n\n")

print(f'First row of the array:')
print(arr[0])
print(f'First column of the array:')
print(arr[:, 0])
print(f'First two rows of the array:')
print(arr[:2])
print(f'First two columns of the array:')
print(arr[:, :2])
print(f'Element at 0th row and 1st column:')
print(arr[0, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indexing in 2D array:
Element at 0th row and 0th column: 1
Element at 0th row and 1st column: 2
Element at last row and last column: 9

Slicing in 2D array:

First row of the array:
[1 2 3]
First column of the array:
[1 4 7]
First two rows of the array:
[[1 2 3]
 [4 5 6]]
First two columns of the array:
[[1 2]
 [4 5]
 [7 8]]
Element at 0th row and 1st column:
2


In [22]:
# Indexing in 3D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr, end="\n\n")
print("Indexing in 3D array:", end="\n\n")
print(f'Element at 0th row, 0th column and 0th depth:')
print(arr[0, 0, 0])

print(f'Element at 1th row, 0th column and 1st depth:')
print(arr[1, 0, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Indexing in 3D array:

Element at 0th row, 0th column and 0th depth:
1
Element at 1th row, 0th column and 1st depth:
8


---