# <font color = "#6585e7"><b>Numpy A to Z</b></font>

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy, short for Numerical Python, is an essential library in the Python ecosystem for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy serves as the foundation for a variety of scientific computing libraries, such as SciPy (for scientific computing), Pandas (for data analysis), and Matplotlib (for data visualization).

### <b>Creating Array in Python</b>

In [1]:
import array

# syntax : 
# array.array(typecode, [Initializers]), typecodes = i, f, d, u, l, b, B, h, H for int, float, double, unicode, long, signed char, unsigned char, short, unsigned short respectively
arr = array.array('i', [1, 2, 3, 4, 5]) # this will create an array of integers
print("The new created array is : ", arr)

The new created array is :  array('i', [1, 2, 3, 4, 5])


In [2]:
arr_float = array.array('f', [1.1, 2.2, 3.3, 4.4, 5.5]) 
print("The new created array is : ", arr_float)

The new created array is :  array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432, 5.5])


In [3]:
a = array.array('i', [1, 2, 3, 4, 5])
b = array.array('i', [6, 7, 8, 9, 10])
c = a + b # concatenation of two arrays
c

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [6]:
# adding the elements of two arrays
d = array.array('i', [0, 0, 0, 0, 0])
for i in range(len(a)):
    d[i] = a[i] + b[i]
print("The new created array is : ", d)

The new created array is :  array('i', [7, 9, 11, 13, 15])


## <b>Creating Numpy array</b>

In [7]:
import numpy as np # np is a standard alias for numpy

### <b>Creating an numpy array using list, tuple, range, etc</b>

In [10]:
l = [1, 2, 3, 4, 5]
arr1 = np.array(l)

t = (1, 2, 3, 4, 5)
arr2 = np.array(t)

arr3 = np.array(range(1, 6))
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


### <b>Creating an numpy array using arange, linspace, etc</b>

In [12]:
arr = np.arange(1, 6) # this will create an array of 1 to 5 like range function
print(arr)

arr = np.linspace(1, 5, 5) # this will create an array of 1 to 5 with 5 equally spaced elements
print(arr)

arr = np.linspace(1, 5, 10) # this will create an array of 1 to 5 with 10 equally spaced elements, difference between two consecutive elements will be same
print(arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### <b>Creating other types of arrays</b>

In [13]:
# creating an array of constant values

arr = np.full(5, 10) # this will create an array of 5 elements with all elements as 10
print(arr)

[10 10 10 10 10]


In [15]:
# creating an array of ones, zeros and empty array

arr = np.ones(5) # this will create an array of 5 elements with all elements as 1
print(arr)

arr = np.zeros(5) # this will create an array of 5 elements with all elements as 0
print(arr)

arr = np.empty(5) # this will create an array of 5 elements with random values
print(arr)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [22]:
arr = np.empty(5, dtype=int) # this will create an array of 5 elements with random values of integer type
print(arr)

[157048576       354         0         0    131074]


### <b>Creating Multidimensional Arrays</b>

In [23]:
# Creaing 2d array
# with 2d list, tuple

l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(l)
print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Creaing 3d array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
zeros = np.zeros((2, 3)) # 2D array of zeros
print("2D array of Zeros:")
print(zeros)

print()
zeros = np.zeros((2, 3, 4)) # 3D array of zeros
print("3D array of Zeros:")
print(zeros)

2D array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

3D array of Zeros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


---

### <b>Shape, Size, Dtype and Ndim</b>

In [32]:
# checking the shape of the array, shape method will return the shape of the array
print(f"Shape of the arr: {arr.shape}")

# checking the size of the array, size method will return the total number of elements in the array
print(f"Size of the arr: {arr.size}")

# checking the dimension of the array, ndim is used to check the dimension of the array
print(f"Dimension of arr: {arr.ndim}")

Shape of the arr: (2, 5)
Size of the arr: 10
Dimension of arr: 2


In [36]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Dimension of arr1: {arr1.ndim}")
print(f"Dimension of arr2: {arr2.ndim}")
print(f"Dimension of arr3: {arr3.ndim}")

Dimension of arr1: 1
Dimension of arr2: 2
Dimension of arr3: 3


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=float)
print(arr)
print(f"Array shape: {arr.shape}")
print(f"Size of Array: {arr.size}")
print(f"Itemsize of the Array: {arr.itemsize}")
print(f"Datatype of the Array: {arr.dtype}")
print(f"Dimension of arr: {arr.ndim}")

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Array shape: (2, 5)
Size of Array: 10
Itemsize of the Array: 8
Datatype of the Array: float64
Dimension of arr: 2


In [35]:
arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]], dtype=float)
print(arr)
print(f"Array shape: {arr.shape}")
print(f"Size of Array: {arr.size}")
print(f"Itemsize of the Array: {arr.itemsize}")
print(f"Datatype of the Array: {arr.dtype}")
print(f"Dimension of arr: {arr.ndim}")

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20.]]]
Array shape: (2, 2, 5)
Size of Array: 20
Itemsize of the Array: 8
Datatype of the Array: float64
Dimension of arr: 3


---